[package]
name = "bfri"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.4.18"
thiserror = "1.0.56"
color-eyre = "0.6.2"
serde = "1.0.196"


